config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students
  resources :classrooms

  root 'students#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  validates :student_id, :course_id, presence: true
  validates_uniqueness_of :course_id, scope: :student_id

  private

  def timestamp_attributes_for_create
    [:entry_at]
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, :description, :status, presence: true
  has_many :classrooms
  has_many :students, through: :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, :register_number, :status, presence: true
  has_many :classrooms
  has_many :courses, through: :classrooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < InheritedResources::Base
  include InheritedResourcesDefaults

  private

  def classroom_params
    params.require(:classroom).permit(:course_id, :student_id)
  end
end

app/controllers/concerns/inherited_resources_defaults.rb
module InheritedResourcesDefaults
  extend ActiveSupport::Concern

  included do
    respond_to :json
  end

  def update
    block_given? ? super : super { collection_url }
  end

  def create
    block_given? ? super : super { collection_url }
  end

  protected

  # def begin_of_association_chain; current_user end

  # def end_of_association_chain; super.page( params[:page] ) end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  include InheritedResourcesDefaults

  private

  def course_params
    params.require(:course).permit(:name, :description, :status)
  end
end

app/controllers/students_controller.rb
class StudentsController < InheritedResources::Base
  include InheritedResourcesDefaults

  private

  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_btn(path)
    content_tag('div', class: 'pull-right') do
      concat(link_to(path, class: 'btn btn-lg btn-success') do
        concat content_tag('span', '', class: 'glyphicon glyphicon-plus')
      end)
    end
  end

  def edit_btn(model)
    link_to [:edit, model], class: 'btn btn-xs btn-info' do
      concat content_tag('span', '', class: 'glyphicon glyphicon-edit')
    end
  end

  def destroy_btn(model)
    link_to [:edit, model], method: :delete, class: 'btn btn-xs btn-danger', data: {confirm: 'Tem Certeza?'} do
      concat content_tag('span', '', class: 'glyphicon glyphicon-trash')
    end
  end
end

app/views/classrooms/_form.html.haml
= simple_form_for(@classroom) do |f|
  = f.error_notification

  .form-inputs
    = f.association :student
    = f.association :course

  .form-actions
    = f.button :submit

app/views/classrooms/edit.html.haml
%h1 Editar Matrícula

= render 'form'

app/views/classrooms/index.html.haml
%h1 Matrículas

= new_btn new_classroom_path

%table.table
  %thead
    %tr
      %th Curso
      %th Estudante
      %th Data
      %th Cancelar
  %tbody
    - @classrooms.each do |classroom|
      %tr
        %td= classroom.course.name
        %td= classroom.student.name
        %td= l classroom.entry_at
        %td
          = link_to classroom_path(classroom), method: :delete, class: 'btn btn-xs btn-danger' do
            %span.glyphicon.glyphicon-trash

app/views/classrooms/new.html.haml
%h1 New Classroom

= render 'form'

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :status, as: :boolean

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

app/views/courses/index.html.haml
%h1 Listar Cursos

= new_btn new_course_path

%table.table
  %thead
    %tr
      %th Nome
      %th Descrição
      %th{width:1}
      %th{width:1}

  %tbody
    - @courses.each do |course|
      %tr
        %td= course.name
        %td= course.description
        %td= edit_btn course
        %td= destroy_btn course

app/views/courses/new.html.haml
%h1 Nova Matrícula

= render 'form'

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @course.name
%p
  %b Description:
  = @course.description
%p
  %b Status:
  = @course.status

= link_to 'Edit', edit_course_path(@course)
\|
= link_to 'Back', courses_path

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to 'Repense', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav
      %li= link_to 'Estudantes', students_path
      %li= link_to 'Cursos', courses_path
      %li= link_to 'Matrículas', classrooms_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Repense
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container
      = yield

app/views/students/_form.html.haml
= simple_form_for(@student) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :register_number
    = f.input :status, as: :boolean

  .form-actions
    = f.button :submit

app/views/students/edit.html.haml
%h1 Editar Estudante

= render 'form'

app/views/students/index.html.haml
%h1 Listar Estudantes

= new_btn new_student_path

%table.table
  %thead
    %tr
      %th Nome
      %th Registro
      %th{width:1}
      %th{width:1}

  %tbody
    - @students.each do |student|
      %tr
        %td= student.name
        %td= student.register_number
        %td= edit_btn student
        %td= destroy_btn student

app/views/students/new.html.haml
%h1 Novo Estudante

= render 'form'

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @student.name
%p
  %b Register number:
  = @student.register_number
%p
  %b Status:
  = @student.status

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path